apiVersion: v1
kind: Service
metadata:
  name: flask-demo-k8s
spec:
  selector:
    app: flask-demo
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  selector:
    matchLabels:
      app: flask-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: flask-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080